### ISSUE TITLE
Parser/Edit

### ISSUE THREAD

**Issue by manuelmerkel** [koppor/adr-manager#19]
Need to implement a parser that can read an adr-markdown-file. Need to parse from md to json and then from json to adr. For adr will be implemented a class to handle the information. The Edit tabs read the information from a selected file and then display it in three different editing modes, from MADR-Edit to Raw-MD. The changes should be reflected in the different modes.

**As a :** User
**I want:** To be able to edit my adr-files.
**So that**: I can see the changes reflected in the different modes and save the changes.

**And i Know I am done when:** A file can be read without parsing-errors. All the information should be saved and visibly in other modes.

**Comment by koppor** [comment]
Discussion: Syntactial level (Markdown headings, structure, ...); semantic level (is the option list the same as the options listed by pros/cons).

In the Java-world I would have used [ANTLR](https://www.antlr.org/) or JavaCC. No clue for JavaScript world

**Comment by koppor** [comment]
One idea for error reporting is as follows:

    1.md -> datamodel -> convert to 1'.md
    diff(1.md, 1'.md) -> this shows the non-imported content

**Comment by KLBa** [comment]
Suggestion for how the user can approve the parser output after parsing md -> adr -> md.

![grafik](https://user-images.githubusercontent.com/44502936/98936268-041c3400-24e5-11eb-92a3-f536c18264d0.png)

Left: Input ADR
Right: Output of Parser
