### ISSUE TITLE
Drag'n'drop of options

### ISSUE THREAD

**Issue by koppor** [koppor/adr-manager#39]
AKA reordering

**Comment by koppor** [comment]
How does it work?

I cannot drag with the version today

![grafik](https://user-images.githubusercontent.com/1366654/102529404-1f5bff80-40a0-11eb-8086-4245ddf0b106.png)

**Comment by koppor** [comment]
Works in professional mode, but not at the mode chosen at startup. Refs #58

**Comment by manuelmerkel** [comment]
Works now in all modes
