### ISSUE TITLE
[0.5pt] Enable addition of other organizations

### ISSUE THREAD

**Issue by koppor** [koppor/adr-manager#44]
As user, I would like to add other organizations than adr and JabRef.

**Comment by koppor** [comment]
Currently, the UI looks as follows:

![grafik](https://user-images.githubusercontent.com/1366654/101278456-a913ef00-37bb-11eb-94e2-c613b239c549.png)

**Comment by manuelmerkel** [comment]
Has been fixed in the current pull request (#53)
