### ISSUE TITLE
[0.5pt] Change logo of application

### ISSUE THREAD

**Issue by koppor** [koppor/adr-manager#45]
Currently, there is the standard vue.js logo:

![grafik](https://user-images.githubusercontent.com/1366654/101278494-e24c5f00-37bb-11eb-8489-e03538d98dc3.png)

We should have an other logo. Maybe just a "D" (for **D**ecisions)

**Comment by KLBa** [comment]
We decided on this logo for now:

![Favicon4](https://user-images.githubusercontent.com/44502936/102485234-9de87b00-4067-11eb-9bd6-bf334b44cacf.png)

**Comment by KLBa** [comment]
The icon should be added:
![grafik](https://user-images.githubusercontent.com/44502936/103666824-6d647480-4f75-11eb-8ec6-9958223601e2.png)

Could you check if it's at `http://localhost:8080/favicon.ico`? That should force your browser to reload the icon.
