### ISSUE TITLE
Conversion of Decision Drivers to Markdown does not work

### ISSUE THREAD

**Issue by koppor** [koppor/adr-manager#51]
ADR screen:

![grafik](https://user-images.githubusercontent.com/1366654/101279441-94872500-37c2-11eb-9ae0-f0423b06506c.png)

Markdown output:

![grafik](https://user-images.githubusercontent.com/1366654/101279451-a10b7d80-37c2-11eb-84cd-20287c036334.png)

**Comment by manuelmerkel** [comment]
Has been fixed in the current pull request (#53 )
